# Generated by Django 2.0.2 on 2018-03-03 23:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('term', '0002_finalindicatorevaluation_indicator'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='finalindicatorevaluation',
            unique_together={('indicator', 'course', 'evaluated')},
        ),
    ]
