# Generated by Django 2.0.2 on 2018-03-07 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('term', '0005_auto_20180306_0112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('updated_ts', models.DateTimeField(auto_now=True)),
                ('score', models.FloatField()),
                ('message', models.CharField(max_length=250, verbose_name='Mensaje')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TempFedbackMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('updated_ts', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(max_length=250, verbose_name='Mensaje')),
                ('fedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='term.Fedback')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TempFedbackScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('updated_ts', models.DateTimeField(auto_now=True)),
                ('value', models.FloatField()),
                ('fedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='term.Fedback')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='course',
            name='subject',
        ),
        migrations.AddField(
            model_name='fedback',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='term.Course'),
        ),
        migrations.AddField(
            model_name='fedback',
            name='evaluated',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fedback_evaluated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fedback',
            name='evaluator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fedback_evaluator', to=settings.AUTH_USER_MODEL),
        ),
    ]
