# Generated by Django 2.0.2 on 2018-03-07 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('term', '0005_auto_20180306_0112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('updated_ts', models.DateTimeField(auto_now=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('message', models.TextField(max_length=500, verbose_name='Mensaje')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='term.Course')),
                ('evaluated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_evaluated', to=settings.AUTH_USER_MODEL)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_evaluator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TempFedbackScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('updated_ts', models.DateTimeField(auto_now=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='term.Feedback')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TempFeedbackMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('updated_ts', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(max_length=500, verbose_name='Mensaje')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='term.Feedback')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
