# Generated by Django 2.0.2 on 2018-03-17 05:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term', '0006_auto_20180307_1612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'curso', 'verbose_name_plural': 'cursos'},
        ),
        migrations.AlterModelOptions(
            name='finalindicatorevaluation',
            options={'verbose_name': 'puntaje de indicador (estudiante - curso)', 'verbose_name_plural': 'puntajes de indicadores (estudiante - curso)'},
        ),
        migrations.AlterModelOptions(
            name='finalscoreevaluation',
            options={'verbose_name': 'nota final (estudiante - curso)', 'verbose_name_plural': 'notas finales (estudiante - curso)'},
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='teachers', to=settings.AUTH_USER_MODEL),
        ),
    ]
