# Generated by Django 2.0.2 on 2018-03-07 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term', '0007_course_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fedback',
            name='message',
            field=models.TextField(max_length=500, verbose_name='Mensaje'),
        ),
        migrations.AlterField(
            model_name='tempfedbackmessage',
            name='message',
            field=models.TextField(max_length=500, verbose_name='Mensaje'),
        ),
    ]
