# Generated by Django 2.0.2 on 2018-03-07 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term', '0008_auto_20180306_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempfedbackscore',
            name='value',
        ),
        migrations.AddField(
            model_name='tempfedbackscore',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fedback',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
