# Generated by Django 2.0.2 on 2018-03-07 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('term', '0009_auto_20180306_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalindicatorevaluation',
            name='fedback',
        ),
        migrations.RemoveField(
            model_name='finalindicatorevaluation',
            name='fedback_score',
        ),
    ]
