# Generated by Django 2.0.2 on 2018-03-17 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180317_0136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'competencia'},
        ),
        migrations.AlterModelOptions(
            name='skillleveldescription',
            options={'verbose_name': 'descripción competencia y nivel', 'verbose_name_plural': 'descripciones competencias y niveles'},
        ),
        migrations.AlterModelOptions(
            name='skillsgroup',
            options={'verbose_name': 'grupo de competencias', 'verbose_name_plural': 'grupos de competencias'},
        ),
        migrations.AlterModelOptions(
            name='subjectsgroup',
            options={'verbose_name': 'grupo de asignaturas', 'verbose_name_plural': 'grupos de asignaturas'},
        ),
    ]
