# Generated by Django 2.0.2 on 2018-03-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180323_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='name',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
