# Generated by Django 2.0.2 on 2018-03-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180323_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(max_length=250, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=250, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=250, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='skillleveldescription',
            name='name',
            field=models.CharField(max_length=250, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='skillsgroup',
            name='name',
            field=models.CharField(max_length=250, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=250, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='subjectsgroup',
            name='name',
            field=models.CharField(max_length=250, verbose_name='nombre'),
        ),
    ]
