# Generated by Django 2.0.2 on 2018-03-01 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilesprogram',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='userprofilesprogram',
            unique_together={('user', 'program')},
        ),
    ]
