# Generated by Django 2.0.2 on 2018-03-01 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20180301_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilesprogram',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles_program', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
    ]
