# Generated by Django 2.0.2 on 2018-03-31 16:00

import apps.base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20180327_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='upload',
            field=models.FileField(default=1, upload_to=apps.base.models.user_directory_path),
            preserve_default=False,
        ),
    ]
