# Generated by Django 2.0.2 on 2018-03-31 16:00

import apps.base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to=apps.base.models.user_directory_path),
        ),
    ]
