# Generated by Django 2.0.2 on 2018-04-14 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_user_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='upload',
            new_name='image_profile',
        ),
    ]
