# Generated by Django 2.0.2 on 2018-03-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('base', '0005_parameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='code',
            field=models.CharField(max_length=100, verbose_name='código'),
        ),
        migrations.AlterUniqueTogether(
            name='parameter',
            unique_together={('code', 'program')},
        ),
    ]
