# Generated by Django 2.0.2 on 2018-04-15 05:18

import apps.base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20180414_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_profile',
            field=models.ImageField(blank=True, null=True, upload_to=apps.base.models.user_directory_path),
        ),
    ]
