# Generated by Django 2.0.2 on 2018-03-03 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20180303_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameter',
            old_name='description',
            new_name='value',
        ),
    ]
