# Generated by Django 2.0.2 on 2018-03-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20180303_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='value',
            field=models.TextField(blank=True, verbose_name='valor'),
        ),
    ]
