# Generated by Django 2.0.2 on 2018-03-29 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180323_0213'),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Subject'),
            preserve_default=False,
        ),
    ]
