# Generated by Django 2.0.2 on 2018-03-17 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campus',
            options={'verbose_name': 'campus', 'verbose_name_plural': 'campus'},
        ),
        migrations.AlterModelOptions(
            name='period',
            options={'verbose_name': 'periodo'},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'verbose_name': 'encuesta'},
        ),
    ]
